### PR TITLE
Bump up to 1.0.1

### PR DESCRIPTION
**Pull request by lbdreyer**
The latest release of nc_time_axis just includes a simple bug fix

### CODE REVIEW

**Comment by lbdreyer** [comment]
@ocefpaf Do you mind merging this in? I think only you and I have merge permissions on this repo

**Comment by ocefpaf** [comment]
No problem. Bur self-merging updates like this is fair game in conda-forge.

**Comment by lbdreyer** [comment]
Thank you!

> self-merging updates like this is fair game in conda-forge

Good to know for future. It does feel a little bit risky though, not having someone check over what you've done.

**Comment by ocefpaf** [comment]
Good to know for future. It does feel a little bit risky though, not having
someone check over what you've done.


When in doubt feel free to ping me. But in when the changes are trivial,
like a version bump, green CIs is all we need.

**Pull request merged**
